const actions = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_ALL_TODOS: 'REMOVE_ALL_TODOS',
  FETCH_DATA_FROM_STORE: 'FETCH_DATA_FROM_STORE',
  DELETE_SINGLE_TODO: 'DELETE_SINGLE_TODO',
  DELETE_SELECTED: 'DELETE_SELECTED',
  UPDATE_TODO: 'UPDATE_TODO',
  CHANGE_COLOR:"CHANGE_COLOR",
  PINNED_TODOS:"PINNED_TODOS",
};
export default actions;
